apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blakpath
resources:
  - namespace.yaml
  - configmap.yaml
  - serviceaccounts.yaml
  - externalsecret.yaml
  - web-deployment.yaml
  - worker-deployment.yaml
  - service-ingress.yaml
  - autoscaling.yaml
images:
  - name: 959038055523.dkr.ecr.ap-southeast-2.amazonaws.com/blakpath/app
    newTag: f00ae65
  - name: 959038055523.dkr.ecr.ap-southeast-2.amazonaws.com/blakpath/worker
    newTag: f00ae65
